// FOOTER
document.write('<div class="footer-border footerhide printhide footer-page">');
document.write('<div class="footer-pad">');
document.write('<table class="fullwidth"><tr><td class="td-top td-left">');
document.write('<table class="footer-links"><tr><td class="td-top td-left footerlinks-1">');
document.write('<div class="footer-title">School<br>');
document.write('</div>');
document.write('<a href="index.htm">Home</a><br>'); 
document.write('<a href="about.htm">About Us</a><br>'); 
document.write('<a href="staff.htm">Our Staff</a><br>'); 
document.write('<a href="news.htm">News</a><br>'); 
document.write('</td><td class="td-top td-left footerlinks-2">'); 
document.write('<div class="footer-title">Facilities<br>'); 
document.write('</div>'); 
document.write('<a href="services.htm">Our Facilities</a><br>'); 
document.write('<a href="press.htm">Press / Testimonials</a><br>'); 
document.write('<a href="staff.htm">Our Staff</a><br>'); 
document.write('<a href="PDFgallery.htm">PDF Downloads</a><br>'); 
document.write('</td><td class="td-top td-left footerlinks-3">'); 
document.write('<div class="footer-title">Contact &amp; Help<br></div>'); 
document.write('<a href="contact.htm">Contact</a><br>'); 
document.write('<a href="site_map.htm">Site Map</a><br>'); 
<!--document.write('<a href="links.htm">Website Links</a><br>'); -->
document.write('<a href="privacy.htm">Privacy Policy</a><br>'); 
document.write('</td></tr></table>');
document.write('<table class="footer-image-table"><tr><td>'); 
document.write('<img src="img/footer/footer-1.jpg" width="100" height="65" class="footer-image blockimage" alt="image">'); 
document.write('</td><td>'); 
document.write('<img src="img/footer/footer-2.jpg" width="100" height="65" class="footer-image blockimage" alt="image">');
document.write('</td><td>');
document.write('<img src="img/footer/footer-3.jpg" width="100" height="65" class="footer-image blockimage" alt="image">');
document.write('</td></tr></table>'); 
document.write('</td><td class="td-middle td-center footer-social">'); 
document.write('<table class="center-div"><tr><td class="td-center">'); 
document.write('<script type="text/javascript" src="js/footer/social-links.js"></script>'); 
document.write('</td></tr></table>'); 
document.write('<!--<a href="http://www.w3.org/" target="_blank"><img src="img/footer/html5.gif" width="80" height="15" class="center-div html5-icon blockimage" alt="Valid HTML5"></a>-->'); 
document.write('</td></tr>'); 
document.write('</table>'); 
document.write('</div>'); 
document.write('</div>'); 